[package]
# Goal is to build "../../wasm-demo/ime_engine.wasm" WebAssembly library file
name = "wasm"
version = "0.0.0"
publish = false

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[profile.release]
incremental = false
lto = true

[dependencies]
ime_engine = { path = "../../" }
